#ifndef DECLARATIONS_H_INCLUDED
#define DECLARATIONS_H_INCLUDED

#define LARGEUR_FENETRE 640
#define HAUTEUR_FENETRE 600
#define LARGEUR_CARTE 140
#define HAUTEUR_CARTE 160
#define ESPACEMENT_VERTICAL 17
#define ESPACEMENT_HORIZONTAL 55

#endif // DECLARATIONS_H_INCLUDED
